import React from "react";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainColor: {
    flex: 1,
    backgroundColor: "#1e1e1e",
  },
  window: {
    width: "100%",
    height: 240,
    backgroundColor: "#fff",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  Resulting: {
    fontSize: 45,
    marginRight: 150,
    textAlign: "right",
  },
  Sections: {
    flexDirection: "row",
  },

  buttonMore: {
    backgroundColor: "#ffd464",
    width: 95,
    height: 70,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
    marginLeft: 29,
    borderRadius: 20,
  },
  buttonMoreText: {
    fontWeight: "bold",
    fontSize: 20,
  },
  buttonX: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 180,
    marginTop: 28,
  },
  buttonXText: {
    fontSize: 38,
    lineHeight: 45,
    fontWeight: "normal",
    transform: [{ rotate: "45deg" }],
  },
  buttonSlash: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 27,
  },
  buttonMinus: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 17,
  },
  buttonConcut: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 17,
  },
  buttonResult: {
    backgroundColor: "#12cc94",
    width: 65,
    height: 103,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 17,
  },
  buttonOperator: {
    fontSize: 38,
  },
  buttonSeven: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
    marginLeft: 29,
  },
  buttonEight: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
    marginLeft: 15,
  },
  buttonNine: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
    marginLeft: 15,
  },
  buttonSix: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonFive: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonFour: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 29,
  },

  buttonThree: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonTwo: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonOne: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 29,
  },
  buttonC: {
    backgroundColor: "#FF5D6E",
    width: 75,
    height: 90,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 29,
  },
  button0: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 90,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonDot: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 90,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonText: {
    fontSize: 30,
  },
});
