import React from "react";
import { StyleSheet } from "react-native";
import { getStatusBarHeight } from "react-native-status-bar-height";

export const styles = StyleSheet.create({
  currencyTextInputView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  CurrencyLabelText: {
    fontSize: 27,
    fontFamily: "StyleScript",
    color: "white",
  },
  currencyTextInput: {
    borderColor: "#0b0b0b",
    borderRadius: 25,
    borderWidth: 2,
    backgroundColor: "#0b0b0b",
    width: 200,
    height: 50,
    color: "white",
    marginTop: 5,
    paddingLeft: 10,
  },

  buttonsMainScreenSectionOne: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  currencyScreen: {
    backgroundColor: "#1e1e1e",
    height: "100%",
    width: "100%",
  },
  currencyMore: {
    backgroundColor: "#ffd464",
    width: 95,
    height: 70,
    alignItems: "center",
    justifyContent: "center",
    marginTop: getStatusBarHeight() + 10,
    marginLeft: 29,
    borderRadius: 20,
  },
  currencyMoreText: {
    fontFamily: "StyleScript",
    fontSize: 27,
  },
  overStatusBar: { flex: 1, backgroundColor: "#1e1e1e" },
  underStatusBar: {
    flex: 1,
    marginTop: getStatusBarHeight(),
    justifyContent: "flex-start",
    padding: 20,
  },
  underStatusBarText: {
    color: "chocolate",
    fontFamily: "StyleScript",
    fontSize: 45,
    textAlign: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalText: {
    marginBottom: 5,
    alignItems: "center",
  },
  modalTextInput: {
    width: "100%",
    borderWidth: 2,
    borderRadius: 25,
    borderColor: "#A6DC8C",
  },
  openButton: {
    backgroundColor: "#F194FF",
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    backgroundColor: "#A6DC8C",
    height: 40,
    width: 90,
    justifyContent: "center",
    textAlign: "center",
  },
  hideButton: {
    backgroundColor: "#F194FF",
    borderRadius: 20,
    marginHorizontal: 25,
    padding: 10,
    elevation: 2,
    backgroundColor: "#A6DC8C",
    height: 40,
    width: 90,
    justifyContent: "space-between",
    marginTop: 20,
  },
  textStyle: {
    color: "black",
    fontWeight: "bold",
    textAlign: "center",
  },
  mainColor: {
    flex: 1,
    backgroundColor: "#1e1e1e",
  },
  ButtonsMainScreen: {
    backgroundColor: "#ffd464",
    borderRadius: 20,
    width: 120,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  calculatorButtonText: {
    fontSize: 27,
    fontFamily: "StyleScript",
  },
  currencyConvertButtonText: {
    fontSize: 27,
    fontFamily: "StyleScript",
  },
  window: {
    width: "100%",
    height: 240,
    backgroundColor: "#fff",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  Resulting: {
    fontSize: 45,
    marginRight: 10,
    textAlign: "right",
    color: "black",
    marginBottom: 15,
  },
  result: {
    fontSize: 65,
    marginRight: 10,
    textAlign: "right",
    marginBottom: 5,
    color: "grey",
  },
  Sections: {
    flexDirection: "row",
  },

  buttonMore: {
    backgroundColor: "#ffd464",
    width: 95,
    height: 70,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
    marginLeft: 29,
    borderRadius: 20,
  },
  buttonMoreText: {
    fontFamily: "StyleScript",
    fontSize: 27,
  },
  buttonX: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 180,
    marginTop: 28,
  },
  buttonXText: {
    fontSize: 38,
    lineHeight: 45,
    fontWeight: "normal",
    transform: [{ rotate: "45deg" }],
  },
  buttonSlash: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 27,
  },
  buttonMinus: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 17,
  },
  buttonConcut: {
    backgroundColor: "#A6DC8C",
    width: 65,
    height: 65,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 17,
  },
  buttonResult: {
    backgroundColor: "#12cc94",
    width: 65,
    height: 103,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 25,
    marginLeft: 20,
    marginTop: 17,
  },
  buttonOperator: {
    fontSize: 38,
  },
  buttonSeven: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
    marginLeft: 29,
  },
  buttonEight: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
    marginLeft: 15,
  },
  buttonNine: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 40,
    marginLeft: 15,
  },
  buttonSix: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonFive: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonFour: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 29,
  },

  buttonThree: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonTwo: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonOne: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 65,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 29,
  },
  buttonC: {
    backgroundColor: "#FF5D6E",
    width: 75,
    height: 90,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 29,
  },
  button0: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 90,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonDot: {
    backgroundColor: "#EAF6F6",
    width: 75,
    height: 90,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 15,
  },
  buttonText: {
    fontSize: 30,
  },
});
